const inputData = `lflZfgnSnlmmlgGfjGthQPtLNsQhvbHLLpSS
zrCVDVFMJTCTcCJMwCThWbtbpbWpPbtbHPLQssLsHP
rBFcrwFzFwwVDcDrzTzJfnRGjllBdGZnnZfhqmdn
FjpnFRDmbRtnbJrFJmSTsGShWVhGqGVVsmqs
ZwPvNPdzNZwfzBNLdNNNNcLvhnQhqMTVsTGSWSqGqTdVWhMT
vgLZHfvLffNLPbggnrbFpJnCbC
hzJzGjGfqmGtDQtDSvVV
plpcMBNBcCTlTgCMbvtrsSVsVJDJlrwDQr
McHBMMcTTHgJnWqnRqjzZnnRzR
ppvsGZhDGprrSjSllwfZ
TTFMMFJMgMHmHmdqdSvNqlSSSNJv
mgBPHTRWFRVcpvsVttppbv
ZZDssfMDMtqqppZLLJzmzSTwNJplTSgpgm
BdCRRHFRbccWWBvBHCdcJVngNVSvTgVNzgNNVmnz
QHFFrBdcGtqPmmQh
qLvQFRgLSSNgqQvRrqLTQvLttwDBFWDwjwFttDdlBBwBwM
nbsmZnbmHbZVCGPVmHWtwlStBDtwBMtwWHMj
CnCbhGCPpPCSnZmrgRNRqNRrLNgrzh
vgLWWHRNLnWwLggWzwLFFzMmBMRMhMhTbhsmmsbbmQTm
rScpJJDDpjtSDPPPJDpjqPCHBBtlTdblmmlhBsMMmTsbmtsl
GHZHCPprSSwgvWNVwVZv
dMrCMJMqvtdFwcjczjQzThtm
gGbLblLpZlHvllQhlQwcjT
GHRWvPRbPHPRvNGbvdRBqdqBBfRqBqnrfF
VsHcljlbhmHbHHlcjVcVShJSCdJCfMrMMQDfRNFCfMRGfNrQ
tGtvLtpgBTGvDMMRdMMgdCNM
pnGnGqGtvtzTLjWqmSSjHhWhWs
NJTDntDNDVjNnjBfjjjcCZCZcVqCSCLqcSScCc
zvhgRgQvvdllgQbHghlvHrRHSScBCRqqwCLGqSMCZCGGGqMZ
pvvrHzdgvlgzQphQsDFmnsNTTtjfjJJmPB
ScnSZSZZlmjmHjjWHHWZftJVJpppwtVVnLJtnptnwt
CFFlQBbbPQqrBwJrJJrGJD
PgTqRddFzgdRPFFbFgqQFgsSjfHWfSHmSMWcjZlmZmjTZM
lzBRtctbnBRBRBBWnDnDWjlLVvwGMrvwrHHQHGmDvHQvHGrV
FsTgFCTSgsCNspzhCGMfTHQVwVMfMmMmrH
hSdSFgghhqpRbLqjntqnPz
DCDnNGFFDQdQmVDNdFVNFccpJLHWSvPLrvvvPtGGhSttLv
sBgTzzZqrBlfljslWBhvHSvPBhSBJSSL
lRlTgMzlzrwRrnmbCMCFnNVMnc
MJQJMJHBrsdrHwts
dbbSVGgbjVqGTVfqddCTpmWWcprgNgWmcWwWswpN
LPdGGdVGPCVdLBlBMlDRRRMD
vdcwZLTdTFFRDHVgmpppMmqZ
jGPzCnQPjlsDVqDpqDHbgP
BjWJrlGQQzrCzBzlzBCGBznzwNRNcwLJdwTJFTHRSTvtLcNN
ngrgqTjJJZnjFJpnqnnVTLzBbbHbLQdLHLHbrdHdHG
lNcltCCtvftfWssPbMQdMBzhbbcBDLdh
PRtWsQCmWsmSsCNCSvCSWlspwgqjqmqjTpnJZwnZVpFwgq
PjWjGDCjmrmWPNmvWDWFmgCNfVJRLfJRfLDLJQlfHplpRbfR
MtZMtcSbccZshTtQTVVTpzHlLRRQLV
cZhbwMnwqsqnhnqtMBnvNFrnGPNPPmgPGCgW
WBjWjWjqZwQJnJZCZZbf
StHSDRPHHcTrTrJpLCCMbrqnJn
RvTTvGqcqTFvSvSRDHvRjlhgWBWBdhjwjGgNjhlj
FSbCqcFsbCPtrcrqhCScbshMjHDGGWBLHBnjGLPBHGGBGnHj
flQdlsgQgGnQHBHjDn
vllgRZdmvsvpgdwZgzJdwRmprqccSFcSShJbTSttqMCrCCch
GwwgCtvHgwcHVVDqpWdfnqVv
sllBsSNBjSrLfqhLgjfqhL
ZbQbZQzgQQPSblBggNQRHGZHHCmwmHFGGcwtJm
CmGVGBTVTmmTWTNLLCVgCSFvDQppQQDDnDQDJpMggfnQft
RrtdqtldPbHzRbnjRfQZjJfMDnMj
wcwhccqrdrrlFmLGCwCtSwtL
pzZznZphZnpcNWSwGwVVPzrPrG
lgFllLLltgbDsrBCwrjWGmwmtw
MgJbDLlMQRJccchrhc
wbbjzZhdGDwLzZSBWqqHmZgssCWqFtMZ
VRJccfvPlTTlQlHQCWQhMMhCCHqQ
RlVfVJcPTVTfvvvJfNJVlcBjGjwhSLdBNGGnjLLBwzGb
bvpqHMVTTpZnqnWRQQQw
tfhFFdSFggfhbldhhZcnRscRcQmnRs
DPzgFJzFLfFbFSgPFgdPglMHpvBpHTCMGpjvMMpLvvNG
JggGLQgQpLpSPRJgGPSnGlFTDBjjRFvRjtBFjWvFjqRj
cmHhZcMHcWjrTBjrvm
dbHwdNNHhwTNThZHdlwQJJwngpgnJGnSPw
DbZjVfjVLhZDLpWPHpMZPmmGNp
lFcJJGcFqnBFqwJCHHMmNHPsdCNp
BlwccRQtBwBrwLGbGhGggzLgzR
RBhZPjlWqgbNbgGLBr
MzSmSzpFdHwpswzzHnzjnvLCbgtrtLGLbJLLJNtJtbwJ
MsSHdmMdpFfmFjpfcPWRhRVZfWQThZ
mqmssPCFhhsJccVg
FTttfwdjjHznJgfngpnc
dNFTjQNRtRNQldRNrRdHMRrlPZqCGlGBCqqZmmbPqDmDCmGW
ZJVRRZZJRcvmPhCJrvhm
PPWQDTfWbnnstlCGvjGrWMGMvr
TbbwddndsnsfDpwFqZFVHBVPqc
tFmpJmgJJgmFDWgRgFrrlGSltSQvZChMtCMM
TLcZHsjLVNBwGQCCGlsCShvh
nqNdwwccBwVLwjjDznZzppbgzFZfDF
qsTqCCCszjlqTssBShlQSSZFgZZhgB
LDPmVgDDJdLPrPgLgPZSFZQfhQGGBQJcSFJS
mvmVbVvtggVtvgdLVvtmptCsNTtjRnpRTTjpsqCp
BdNPLnmFvLFNgnmBmnFGnwSZZZWwqWgqjwWssTHWSS
bJhMzhbVMbDCcVpZtjHMqTMwtttSjH
hzclfCppVqQfbzQVbpzPQLNFBdrvdNGGBnmrmP
nLVLzBDJCCHqdLncqVJgSsDlGsbssmvvvbvbff
jMNHFWNTZZNwMPrPWrrPMMrrvSllbgsllfgbgvQsvGmglZbv
RjPjrjRPtNrwHhBtncCJtJtL
jbhhjhNjvqNbmjMjqhtCFdmPFdlzJzfFfJQJfR
GBBZWrZWgpSsnSngrrSgHzFzFFdClzfFQFlRZftQPR
TrGTrGWHpHWGHWVWsngprHpLbLLVvcqMcNbVNLhwVNbtNb
sQDvDmDLQFDRsdchzhBczLhhPhVz
MbGGMjjGZSjvfHvHSbfwBqcPnqqcPVhPNnqnzjcn
ZwMMHrWvSHbfJfTrbJwSMMfMsQDtsFRptlpdCRpWmptQDRmC
TwMHdcTznLqzTrHdzzzHTdgMRQWRhJhNjjvgQvQQWNjl
tbfsVbDCVSSDtSPQJWPvRNhQtghN
FVGBpGCVFCbfCbVbZCSHqmwqcqLcdHJGwHqqTd
lTlGfjLGwHNMggscsDRwsC
MrFtrzZZPZrtVQtnrrFdQhhDPDSphgDRhDcsCCgWpW
ZJmJVzVVJFHfGbqJGMLv
zsFZVjzlHPfTzGfLGt
mdrrmdMMcBcmNqNbPqfRDLPWPlqTWD
BNQhmmrBrQghgSmNBQQSmvwssjZZSJHljJFFHZJvZV
rLZCsZdMJfdNCsfZMrLdFmssnwgTRQgBBwgRwcngTNVRVQjV
StqDHlStDPgRTqcwjT
GlDGDhbpHhvSHWlzbWlhpzhJdrFLrCLmvdmFZsmJJjJfdv
pJHJMJsJjSMFdHhszFvMhlmmGNlSmmBGllWmVlwcTw
ZqZRDrZCZDtPDPDrCngrnnPQGVmGHVBWGWtGmWVwVlmTlGNl
ZQPgRqrrQPqLnrLMvLphHdvdjpJddb
NwbBjljFbcjtTcccqW
RHZrPHPpNgZTzTqc
sfrPdmPdpsmPPPrfQPVGlwGVBwbGVnFlNQCG
hQdNTlzhdTvrhdnTBqcWBLsBHgWQgBPg
zwzRDbDfqZBLHDLB
wFbFmjjRzfmjGGMGMfmJwwGCCnvNhpvSCNnrvJvCprnnSp
zshNNJbwGFJfGJzzzNRnHGnCnRHcRPgTmPmn
LMDVtZLStrrZClBrVDllLSBWRPTPPRRPmgWPVmPTPHTWgR
SDSqLMlrtLlLtrBqBdlMZjvffCNzwvhjvvzhdfNhvf
SLQmGBmhLSLQTBGBGwdwpJjwwQjwcVpJZJ
sNrWrWPNbHghrbgnNNzbWbFWdZpMpzVpdMZMzMMVZcwwJdwd
frrPNNWshWhhHDvDGDRSBSRvttqv
FJqpgvhJJRjFjZTqDsMHrzwjsSsSszMrMm
PPPQWGtnbbfBmPsFswwsMrcc
QfBtbldtWQfbWbnfGlFqZppvpFZZLhFlpq
ZqSMZHHCMpHTZTWmFTFZPZQJBgVGVJQvVVSDBvBtcBBG
RNsndwsNjsbsgGCgjQBttcBg
NRszRRNzLNNNwNfhCCrfdmTqFZllFFHFFpWhlTmWpq
llbbzDmSspGRpHpzsldzRRsVtFBBFJMMVVFLTTTMVtLTDM
cqgjqvNgvqCjQZqgGGnhMTnMJVLBLMtFhhVFWB
PfGGvQrPCjvjZgGCCCZZZbSmmmHlRpprlHrHwssSRr
mRmpFpWpfMMgLnmS
CdCsqzdRzqStLjSqfMnL
wQRHdTzCQbzCwsTrZBlFZGpVlpFGQD
qnMTnTVSTPTHTHcMZMvVpmppmFmVzFLLFLlFpG
gBjDsjRRwhDDghthwwWZwLmpmwWWLWLbGZ
NhZtZtBgPTNJJNTS
jLjjmpHvzvZrfzQjmfHHWrfbqblLsSlTsqsgqPJbPqVglb
FBcCwDwtwgcgnCwcGchtJSsRqVRVJPPqDlbSDRPq
MBhthFNtMGCwhcwnpQfWjNrQprpvzpgQ
RfCnWfnhCbwHgWjzBgzB
PsVqDsSTshsgszpsph
DPDvTVtTShhSZhmqSvLlQJFnQJJZnbCnlCCZ
pRRdJngltnwwvTNSWqWffqgBqD
HQGcsdrjzMDDBfGMGG
FLhsdbzCLLHjhntpVnRPRvZV
gZNwQHHNRlGvhvhGRvRb
dpSSBDrzdCfcSzfrzZrfCfMbthWWWPttDthvMFWvvvPj
ZdpBpZCrssBJZfSJBzBdCTcnmQwmnVVlmqTQTTQlHLwNnN
ssCpTttVVVpzZDVvRpCsRtDgWBWBBFBJvvJHMBghGghrMJ
lwLmNNLwSblbmSQLfhJHZgHrHhhJJhHHmW
QLSdbdPqndlNlLdSLNQncpRtRTcRVTPPZRCjVCcc
wzzJclzcTThvWSSCqRlQSsNN
rDpVjpVVDpsQSRDRfQmm
GLbjrLpFbgLVLLgdbjVpchcFZhvBwJvtvtJcZwRB
wPgZgLVMfWVTgmTZZZftJjtfjtJCcdpjdCqc
zGGbQQnQGvBBhGQvvvBBSBvQdhdqqCpdddDmJlCcDjCtJdmJ
HszzHBzQBSmGSwTWgswZPWTVgZ
GDFvzCFdrszSdNJrFfjjfqZjRfsjpqmcwZ
WbbVtVnBPWMgBLMBnQQnBQHcjfjpZRwqcwMfcNTZRqqNmT
WQQnVVPHtggLghWWhHnPVQbvlJhSlrvJDlFGJDdDCzGNFF
dVhTBjBHtTVqWRJZRqhJZQ
brSDTbDfcCwDzfCSbwMQnlqCRJnMgWWnZngM
DFwNSrwNwbDzbFTTFtjmBpVdGpHs
dPQfdfTzDrFDmFDBgBFj
RlJRclcswJRvnwPcpjbjbbCZjFjbBmsbFZ
pqncGlcRJpHGpllGHhvPhRTHrQrttVVfrdQzfrTdftfV
RCzTzRMTfCfRRDzRfhSmZZlCslBbZZBVtZBZsqBL
nvvJPpdcFnPcWnFnVZvBqVlZMbZBNVlV
FpWPMdjdPhSTmwfSjD
NDJjNHLLNWjcLLWCLJLZjLDtRqqtgtMqgtqnRqnSRgggtZ
BwrlfFwmQwhwfPBFhsBdFmbQggCgqQVtbRSqttqMngnp
llPPwsPlGshBJGWJLcHvCzNv
rBvTmwdTSbnrvVWsWVftGfJQGT
gNRLLjlPRWnFVRFDFW
lpCpPNZqZCdvdppnSnBr
ShRdCrJgHClZJtZDGMMz
LvqVVTTNbVPLQNFTnwwMtzFZGDDwmtnM
VLbNvpPvTNVqVbbNpbVPGNLPrRWrcRCWdSrCjWSHcHSdWpCh
tNmZnLSZPFLDnLTmhJMWczQdhmWhWH
bGqbgrpsCsWhcChNQfJz
vwlNbppsRGRRSSSDvjTjLZjZ
zgMZhgfBtftSZQQmLHpSWH
cdqcqnrJVGjjqPVjrPnfpJmsQHQQpsSsbsSDmm
NNnrNqNlrNcPTlBvBvgggfMv
llPrrLHBHCrRRBjrHCjBdrPmvJZzZgZbmgJlZmZhMhhmvh
pNDstVtNtGFNSDFScQtfwzzFJwmJhgqzbMwqZJmh
fpNsptGtQcTsSTccprddCWPrWdTRBMMCMd
TTtDVqTsTcJFgbCqmbCq
NWZQnllzfBFZPBGWQGzFPFRNNgHbHrrwbNrmCbggJRHR
nBZjGFjMQBMPZnjfWjstpcctttvVtcTttMpL
qphVCCwnHqhnRVznFwvLtBTLDTWZtwLWWS
JmdlsdlsjfJfrtjTcvtctDZSSB
rsmfPGbrPbPJfPmrsgMrdJdlFTHhFCqhNqVHnNHHCFznhphG
JsWFMJJzrhSSdFdldmmdmdQc
qLLgCVTgLbBvqsQPVdQGcRRmQmdc
bBCBgCCDbLDqTvqqjpShHfzrzMfjtHHSHsfz
nvFSBFlvvgQFFBzQnlQglmRRzqwsrrMJJMrsMqrfrwzf
CjZNCNhLDNbPZZLZZhwVjpcfrqRhsdJqdsshRTTdqJrJ
jNNDDppjpjDWNVLCVVDpGVVPBFtlSQFWvvQvSSQHSgwQnvtB
WhrQWBRWwhzgmpnSpH
LqMVsJVvFMJLJMsfNjsTJvCgFbSmzgpSHzmngHbGPCbm
jvMjjtqVjTRnwZQwBWwt
jfTWSGSTTWhgcngQfbtJfNzztBQBzz
pVVwsdppRVPLVmPsVVHsjPLPzQdzBzQFzFBNNrJZZQBzbbFF
VmsqHmjHmpvGDSWDvlclSl
PNZfTFSFfTFGCHqqmbFm
WjzRWrjVgnjzplrWWjJVppgGPGsgstmPCCtcmssQqGQt
pzjzJVvnzJjWvpPlnVRVrvnlTDLNNhwfdNZLfMZLwLhTNvTw
QFrQZMFVrVpVszzcNTdMRCCb
SvljGmlvLfwLhLLLHlHdNzsRthhbbRccRCRNbC
LfwlDmlvGBSjjlLLgpPpFJqgQndQgZBJ
RBjPRHdjPfqQcfhcdv
SngFcJZJlcnctSlhhsQvGsDGDsDnfs
pSmFgSWNJFNtStrmNtpCCjPVcbjjHbcWTBHBHL
vGjqCPqNPGFGNftLwmZwfQNTLp
hrdBCSHcCJJcCBShJswmLQpLbbQZTLLJmmZp
BdHHSzrBWdzchzzCcdzHddcDVWFnjPjllGggVlWljPFFFWPM
hBtZZnpbhbPZJbnhDtPnpBtpfjfNNzrrCzjFzFzFTjfjjWzJ
gHllMqRSmqcqMTdggMqHlcFzRrFQWNfvrRvzQrWjWvWf
gwqlgHmmdsgwlwMHZtpsbBbtDBThbBht
CsDLFFLFCvczsCsJrCrJJLRgbQQgmMmPbDDQbPnMgMmg
VlwNBNVhjNVNWBwWjtbRMRZzPmQnfQMPnlZP
VWWSSwGTwtwWWNVwwpqJJrcJGvzqCJCqJF
wLwSSbzwCvddlvvlSj
THnQnnHttcvpQzrZRllZ
sTntBHTnVbPbgzsbgL
FwHgrHvFQQwpHhNhTBLdpNNNLd
fCGqCVtszfSslCSzSGsfCssjNTqLTdmjNLBLdnTTTMTjTg
DccfslfgRSSVVzlcSVtzDRVHwQZFrwwvwFWbbbRRWwrFJb
CwwWwwFNRpFFpZQHtsmfqbQDTQTTqb
VcjzLjGjzGjGjVjLdzqmDqHrsmsqGRrHqGqH
RjdVlgdnljlBnSgPCpNwwMWwMM
tCCtqtbPGzsSQVzQTq
mzMmHMpRsRQTsFFV
DpzDwgdMzMLppNmNpDpfgrbhLcGtPrbtrbrbhnbBcC
BvsQBBBLvDQGjDvSQLTvrHprHlRpVlVllgRbRbHPqq
MMMMCpfJFZZMmCzwpVPCWRtHgqWgqClgtt
FwzmfzhFFdFcpvSDSBDThs
fQrGQbFFFrHHtlHPclzzPLvc
mTnwpNCCqMqjmCThpTpSvvtBczstlLznvsztsPPP
mCpTNhmmpCqCmjmpTjmLCpSJQZVfFVrDVfffFFgfgJQFdbgG
GmWjRBSfttcGfRcSclVVJqsTMllsgJVMVZwV
pPFNpfNCdNzCVMTTNqVssqJN
dzPfHCLLhdjjLGRnmnmr
GPhPfGWgggfslffPsVPGsqJMzLQJtBprwQJJGQwLpQrw
ZNdmvbDDbNvHbmZCcJQwMmzMwWWQrrwttp
bvdDNdnvNbnHDdnDHHRSbnqhqhWfjWFVTVhRVjfjFTfP
hTThfWNCDRfsVCDhpgzgbpPZZwbnZQns
GSjGGcCBGmdjdSlGBcmZwzJzpPpJzwPwQbzgPd
BGmcrcStcMMMmrSLmSMCvFVRFDhfFhhNDWWTqFqTvf
ZmjDTTbmqQCCQQSwvhsL
FGVJPmPmtRVRsCvvRLwwhC
JgdHJgmfbjzTpTMf
fTbsVCsssgLNrfNrgm
zQvzZlRvddvpNLpZrMNNLZ
HLvWFHHlFQvzHnnlnvQqhzWvstBwbGVtstjGqjjwqGGCcwGq
JNpNdzzdJhNnfNGBZLqZqlhvSZSG
QswtcmmwwmTmwwcwZSLlZLDSvSvlBZQD
FsVFBbFgFsPwtVBTwgTPcsmpzdNngfzfpCzJdzCJzNCndn
qcvrLBppgpWWWgLcpzPfhNDqdzqwDDzwhV
MZFjFnHFMHbMntMtnwStfddPhDffDfzDfS
QmnjMZnlHjmnMGFnFlMmjlZWzLgsGgcrspBBLCBcgvgBRC
sdfWHjZfrZrSPMCQ
zqtWRDDDRMbrQJPQ
zwhwzmqwzmFpWzvFqBmFvjNHlHfgVLBgdfVfNVjLsl
lRlBTlvlZfhtbGBWtFBz
cqCNjjqjrNrcNjwDqNPCVrSQStSWshFhtQhbQzGzmFCG
HjPPzMcdNqjcNHMqPjdpgpZflfdgnTfdlvlJ
VpwQJVRtHplnnwtppHhqWBCfVdNNPqPBPWsBDq
jzLZCrvvrZjZvqNffvDNDcWDWd
LTrZZLFZbgTzgjZZjFClJhTHTplQpmnQlpmpQR
JGJnSWLGSpWHVHwGGJHpZdwPdTTPMdTMDdlzccPMPv
gqrrmtbrbgggqgBtqmRSrFgNCzvMDvlMPDdddvzBcPMMMDBd
gjrmRgmtRggFtqjbhgbjrtnJJHWLHQWZZLhZsLLGHhSL
BtTDNggLRPdWQHqggg
wrVpVVlCJVGMMJVdHWSdPSqqRwSQSP
vCVrpvvGjlphBRmZBhmBhBND
lqDcZGcSSqSqbDnccSLJgHgLRfnvvJRLmvWJ
FVCFPChQzVhmsFBgddRgJBfdNfJdfv
FzCpmTQzjQCThppTSttqDccMTDGcDG
QCSGBGCrCsMBTCQwMGSfvvLNNnnVLDlNVNDdVdlr
ZHtPffjWbqgtmnNdvljFnFhdVv
JRWbmgmRJtmJMGGwSBBRRRfQ
LqNrCfCQQhtgnPnc
JWBrWrVlbWgbbtcb
VwvTBprdrVJVNLNMNNqfqpjN
bjVqdHrdqVHPsPNbqHbqNdjFGRwRGlttRtMtRtFFGMLHJw
cfSpZnBZWQBZJlGRJJcwGMGL
WWBhTMgDTZghVjgjssbrbddd
`

const inputDataArray = inputData.split("\n");

const splitInputData = (array) => {
  const splittedInputArray = [];
  for (let i = 0; i < array.length; i++) {
    let startIndex = 0;
    let halfIndex = array[i].length / 2;
    let endIndex = array[i].length;

    const firstPart = array[i].slice(startIndex, halfIndex);
    const secondPart = array[i].slice(halfIndex, endIndex);
    if (firstPart !== "" && secondPart !== "") {
      splittedInputArray.push([firstPart, secondPart]);
    }
  }
  return splittedInputArray;
};

const findMatch = (string1, string2) => {
  if (string1 && string2) {
    for (let i = 0; i < string1.length; i++) {
      if (string2.includes(string1[i])) {
        return string1[i];
      }
    }
  }
};

// find a match letter in two string
const findMatchedLetters = (arr, findMatchFn) => {
  let matchedLetterList = [];
  for (let i = 0; i < arr.length; i++) {
    for (let j = 0; j < 1; j++) {
      const matchedLetter = findMatchFn(arr[i][j], arr[i][j + 1]);
      matchedLetterList.push(matchedLetter);
    }
  }
  return matchedLetterList;
};

const assignLettersToNumbers = (arr) => {
  const letters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
  const alphabetArray = letters.split("");
  let sumOfIndex = 0;
  for (let i = 0; i < arr.length; i++) {
    const letter = arr[i];
    const index = alphabetArray.indexOf(letter) + 1; // added plus one to match the question pattern
    // console.log(index);
    sumOfIndex = sumOfIndex + index;
  }
  return sumOfIndex
};

const splittedArray = splitInputData(inputDataArray);
const matchedLetterList = findMatchedLetters(splittedArray, findMatch);
const sumOfLetters = assignLettersToNumbers(matchedLetterList);
console.log(sumOfLetters);
